# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89e519f47ca20ef00f5310afa9e5ee7fb3b63a7bcad3ea75976901a97406e15d57d22e00cf1efef440f1b64b0e20c12718257542ed1ec2291df4ab3494fdd6e1

test:
  secret_key_base: 3cea52aceb726831b6fa7adce72f3c821b7af7316958aee3c447ac9dc3eab5fceaa795fab208cc9f5ad3da7f2e64f021283231378edb11f19f5c18b06298e8aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
